name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Dependencies
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
    # - name: Wait for MySQL to be ready
    #   run: |
    #     timeout=300
    #     while ! mysqladmin ping -hmysql -uroot -proot --silent; do
    #       sleep 5
    #       timeout=$((timeout-5))
    #       if [ $timeout -le 0 ]; then
    #         echo "Timeout waiting for MySQL to be ready."
    #         exit 1
    #       fi
    #     done
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite

    # - name: Run Migrations
    #   run: php artisan migrate 
    # - name: Run Seeders
    #   run: php artisan db:seed 
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     MYSQL_DATABASE: test_db
    #     DB_USERNAME: user
    #     DB_PASSWORD: secretroot
    #     DB_PORT: ${{ job.services.mysql.ports[3306] }}
    #   run: vendor/bin/phpunit
